In [20]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
data = pd.read_csv("income_evaluation.csv")
data

age          workclass   fnlwgt    education   education-num  \
0       39          State-gov    77516    Bachelors              13   
1       50   Self-emp-not-inc    83311    Bachelors              13   
2       38            Private   215646      HS-grad               9   
3       53            Private   234721         11th               7   
4       28            Private   338409    Bachelors              13   
...    ...                ...      ...          ...             ...   
32556   27            Private   257302   Assoc-acdm              12   
32557   40            Private   154374      HS-grad               9   
32558   58            Private   151910      HS-grad               9   
32559   22            Private   201490      HS-grad               9   
32560   52       Self-emp-inc   287927      HS-grad               9   

            marital-status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex   capital-gain   capital-loss   hours-per-week  native-country  \
0         Male           2174              0               40   United-States   
1         Male              0              0               13   United-States   
2         Male              0              0               40   United-States   
3         Male              0              0               40   United-States   
4       Female              0              0               40            Cuba   
...        ...            ...            ...              ...             ...   
32556   Female              0              0               38   United-States   
32557     Male              0              0               40   United-States   
32558   Female              0              0               40   United-States   
32559     Male              0              0               20   United-States   
32560   Female          15024              0               40   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [36]:
x = data.iloc[:,[0,2,4,10,11,12]].values
y = data.iloc[:,14].values

In [37]:
x

array([[    39,  77516,     13,   2174,      0,     40],
       [    50,  83311,     13,      0,      0,     13],
       [    38, 215646,      9,      0,      0,     40],
       ...,
       [    58, 151910,      9,      0,      0,     40],
       [    22, 201490,      9,      0,      0,     20],
       [    52, 287927,      9,  15024,      0,     40]])

In [38]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [39]:
x_train

array([[    22, 274103,     13,      0,      0,     10],
       [    20, 143062,     10,      0,      0,     40],
       [    31, 199368,     13,      0,      0,     50],
       ...,
       [    36, 355053,      9,      0,      0,     28],
       [    21, 236769,      4,      0,      0,     40],
       [    41, 342164,     10,      0,      0,     15]])

In [40]:
x_test

array([[    47, 214702,      9,      0,      0,     37],
       [    35,  99146,      9,      0,      0,     50],
       [    42, 404573,     15,      0,      0,     40],
       ...,
       [    61,  73809,     10,      0,      0,     40],
       [    24, 450695,     10,      0,      0,     35],
       [    23,  91189,     10,      0,      0,     40]])

In [41]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [42]:
#SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
#    kernel='linear', max_iter=-1, probability=False, random_state=0,shrinking=True, tol=0.001, verbose=False)
from sklearn.svm import SVC
model = SVC()
model.fit(x_train, y_train)

SVC()

In [44]:
#Predicting the test set result  
y_pred= model.predict(x_test)  
y_pred

array([' <=50K', ' <=50K', ' >50K', ..., ' <=50K', ' <=50K', ' <=50K'],
      dtype=object)

In [46]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_pred,y_test)
print(len(y_pred))
cm

6513


array([[4763, 1004],
       [ 149,  597]])